/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DataLiquidityPoolsRootStorageV1 } from "./DataLiquidityPoolsRootStorageV1";
export type { IDataLiquidityPoolsRoot } from "./IDataLiquidityPoolsRoot";
